var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,g){a instanceof String&&(a=String(a));for(var h=a.length,c=0;c<h;c++){var f=a[c];if(b.call(g,f,c,a))return{i:c,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,g){a!=Array.prototype&&a!=Object.prototype&&(a[b]=g.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var g=a[b];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,g,h){if(b){g=$jscomp.global;a=a.split(".");for(h=0;h<a.length-1;h++){var c=a[h];c in g||(g[c]={});g=g[c]}a=a[a.length-1];h=g[a];b=b(h);b!=h&&null!=b&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,g){return $jscomp.findInternal(this,a,g).v}},"es6","es3");
(function(a){"object"==typeof exports&&"object"==typeof module?a(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],a):a(CodeMirror)})(function(a){function b(c,a,q,b){this.atOccurrence=!1;this.doc=c;null==b&&"string"==typeof a&&(b=!1);q=q?c.clipPos(q):h(0,0);this.pos={from:q,to:q};if("string"!=typeof a)a.global||(a=new RegExp(a.source,a.ignoreCase?"ig":"g")),this.matches=function(m,e){if(m){a.lastIndex=0;m=c.getLine(e.line).slice(0,e.ch);for(var k=
0,d,f;;){a.lastIndex=k;k=a.exec(m);if(!k)break;d=k;f=d.index;k=d.index+(d[0].length||1);if(k==m.length)break}(k=d&&d[0].length||0)||(0==f&&0==m.length?d=void 0:f!=c.getLine(e.line).length&&k++)}else a.lastIndex=e.ch,m=c.getLine(e.line),k=(d=a.exec(m))&&d[0].length||0,f=d&&d.index,f+k==m.length||k||(k=1);if(d&&k)return{from:h(e.line,f),to:h(e.line,f+k),match:d}};else{var f=a;b&&(a=a.toLowerCase());var n=b?function(a){return a.toLowerCase()}:function(a){return a},l=a.split("\n");if(1==l.length)this.matches=
a.length?function(b,e){if(b){b=c.getLine(e.line).slice(0,e.ch);var k=n(b),d=k.lastIndexOf(a);if(-1<d)return d=g(b,k,d),{from:h(e.line,d),to:h(e.line,d+f.length)}}else if(b=c.getLine(e.line).slice(e.ch),k=n(b),d=k.indexOf(a),-1<d)return d=g(b,k,d)+e.ch,{from:h(e.line,d),to:h(e.line,d+f.length)}}:function(){};else{var p=f.split("\n");this.matches=function(a,e){var f=l.length-1;if(a){if(!(e.line-(l.length-1)<c.firstLine()||n(c.getLine(e.line).slice(0,p[f].length))!=l[l.length-1])){a=h(e.line,p[f].length);
e=e.line-1;for(var d=f-1;1<=d;--d,--e)if(l[d]!=n(c.getLine(e)))return;d=c.getLine(e);var b=d.length-p[0].length;return n(d.slice(b))!=l[0]?void 0:{from:h(e,b),to:a}}}else if(!(e.line+(l.length-1)>c.lastLine())&&(d=c.getLine(e.line),b=d.length-p[0].length,n(d.slice(b))==l[0])){a=h(e.line,b);e=e.line+1;for(d=1;d<f;++d,++e)if(l[d]!=n(c.getLine(e)))return;return n(c.getLine(e).slice(0,p[f].length))!=l[f]?void 0:{from:a,to:h(e,p[f].length)}}}}}}function g(a,f,b){if(a.length==f.length)return b;for(f=Math.min(b,
a.length);;){var c=a.slice(0,f).toLowerCase().length;if(c<b)++f;else if(c>b)--f;else return f}}var h=a.Pos;b.prototype={findNext:function(){return this.find(!1)},findPrevious:function(){return this.find(!0)},find:function(a){function c(a){a=h(a,0);b.pos={from:a,to:a};return b.atOccurrence=!1}for(var b=this,g=this.doc.clipPos(a?this.pos.from:this.pos.to);;){if(this.pos=this.matches(a,g))return this.atOccurrence=!0,this.pos.match||!0;if(a){if(!g.line)return c(0);g=h(g.line-1,this.doc.getLine(g.line-
1).length)}else{var r=this.doc.lineCount();if(g.line==r-1)return c(r);g=h(g.line+1,0)}}},from:function(){if(this.atOccurrence)return this.pos.from},to:function(){if(this.atOccurrence)return this.pos.to},replace:function(c,b){this.atOccurrence&&(c=a.splitLines(c),this.doc.replaceRange(c,this.pos.from,this.pos.to,b),this.pos.to=h(this.pos.from.line+c.length-1,c[c.length-1].length+(1==c.length?this.pos.from.ch:0)))}};a.defineExtension("getSearchCursor",function(a,f,g){return new b(this.doc,a,f,g)});
a.defineDocExtension("getSearchCursor",function(a,f,g){return new b(this,a,f,g)});a.defineExtension("selectMatches",function(b,f){var c=[];for(b=this.getSearchCursor(b,this.getCursor("from"),f);b.findNext()&&!(0<a.cmpPos(b.to(),this.getCursor("to")));)c.push({anchor:b.from(),head:b.to()});c.length&&this.setSelections(c,0)})});
