(function(f){"object"==typeof exports&&"object"==typeof module?f(require("../../lib/codemirror"),require("./searchcursor"),require("../dialog/dialog")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","./searchcursor","../dialog/dialog"],f):f(CodeMirror)})(function(f){function v(a,b){"string"==typeof a?a=RegExp(a.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&"),b?"gi":"g"):a.global||(a=RegExp(a.source,a.ignoreCase?"gi":"g"));return{token:function(b){a.lastIndex=b.pos;var c=
a.exec(b.string);if(c&&c.index==b.pos)return b.pos+=c[0].length||1,"searching";c?b.pos=c.index:b.skipToEnd()}}}function w(){this.overlay=this.posFrom=this.posTo=this.lastQuery=this.query=null}function h(a){return a.state.search||(a.state.search=new w)}function k(a){return"string"==typeof a&&a==a.toLowerCase()}function i(a,b,d){return a.getSearchCursor(b,d,k(b))}function x(a,b,d,c,e){a.openDialog(b,c,{value:d,selectValueOnOpen:!0,closeOnEnter:!1,onClose:function(){j(a)},onKeyDown:e})}function o(a,
b,d,c,e){a.openDialog?a.openDialog(b,e,{value:c,selectValueOnOpen:!0}):e(prompt(d,c))}function y(a,b,d,c){if(a.openConfirm)a.openConfirm(b,c);else if(confirm(d))c[0]()}function q(a){return a.replace(/\\(.)/g,function(a,d){return"n"==d?"\n":"r"==d?"\r":d})}function r(a){var b=a.match(/^\/(.*)\/([a-z]*)$/);if(b)try{a=RegExp(b[1],-1==b[2].indexOf("i")?"":"i")}catch(d){}else a=q(a);if("string"==typeof a?""==a:a.test(""))a=/x^/;return a}function l(a,b,d){b.queryText=d;b.query=r(d);a.removeOverlay(b.overlay,
k(b.query));b.overlay=v(b.query,k(b.query));a.addOverlay(b.overlay);a.showMatchesOnScrollbar&&(b.annotate&&(b.annotate.clear(),b.annotate=null),b.annotate=a.showMatchesOnScrollbar(b.query,k(b.query)))}function g(a,b,d,c){var e=h(a);if(e.query)return m(a,b);var n=a.getSelection()||e.lastQuery;if(d&&a.openDialog){var p=null,g=function(b,c){f.e_stop(c);b&&(b!=e.queryText&&(l(a,e,b),e.posFrom=e.posTo=a.getCursor()),p&&(p.style.opacity=1),m(a,c.shiftKey,function(b,e){var c;if(3>e.line&&document.querySelector&&
(c=a.display.wrapper.querySelector(".CodeMirror-dialog"))&&c.getBoundingClientRect().bottom-4>a.cursorCoords(e,"window").top)(p=c).style.opacity=0.4}))};x(a,s,n,g,function(b,e){var c=f.keyName(b),d=f.keyMap[a.getOption("keyMap")][c];d||(d=a.getOption("extraKeys")[c]);if("findNext"==d||"findPrev"==d||"findPersistentNext"==d||"findPersistentPrev"==d)f.e_stop(b),l(a,h(a),e),a.execCommand(d);else if("find"==d||"findPersistent"==d)f.e_stop(b),g(e,b)});c&&n&&(l(a,e,n),m(a,b))}else o(a,s,"Search for:",n,
function(c){c&&!e.query&&a.operation(function(){l(a,e,c);e.posFrom=e.posTo=a.getCursor();m(a,b)})})}function m(a,b,d){a.operation(function(){var c=h(a),e=i(a,c.query,b?c.posFrom:c.posTo);if(!e.find(b)&&(e=i(a,c.query,b?f.Pos(a.lastLine()):f.Pos(a.firstLine(),0)),!e.find(b)))return;a.setSelection(e.from(),e.to());a.scrollIntoView({from:e.from(),to:e.to()},20);c.posFrom=e.from();c.posTo=e.to();d&&d(e.from(),e.to())})}function j(a){a.operation(function(){var b=h(a);if(b.lastQuery=b.query)b.query=b.queryText=
null,a.removeOverlay(b.overlay),b.annotate&&(b.annotate.clear(),b.annotate=null)})}function t(a,b,d){a.operation(function(){for(var c=i(a,b);c.findNext();)if("string"!=typeof b){var e=a.getRange(c.from(),c.to()).match(b);c.replace(d.replace(/\$(\d)/g,function(a,b){return e[b]}))}else c.replace(d)})}function u(a,b){if(!a.getOption("readOnly")){var d=a.getSelection()||h(a).lastQuery,c=b?"Replace all:":"Replace:";o(a,c+z,c,d,function(e){e&&(e=r(e),o(a,A,"Replace with:","",function(c){c=q(c);if(b)t(a,
e,c);else{j(a);var d=i(a,e,a.getCursor("from")),f=function(){var b=d.from(),h;if(!(h=d.findNext()))if(d=i(a,e),!(h=d.findNext())||b&&d.from().line==b.line&&d.from().ch==b.ch)return;a.setSelection(d.from(),d.to());a.scrollIntoView({from:d.from(),to:d.to()});y(a,B,"Replace?",[function(){g(h)},f,function(){t(a,e,c)}])},g=function(a){d.replace("string"==typeof e?c:c.replace(/\$(\d)/g,function(b,c){return a[c]}));f()};f()}}))})}}var s='Search: <input type="text" style="width: 10em" class="CodeMirror-search-field"/> <span style="color: #888" class="CodeMirror-search-hint">(Use /re/ syntax for regexp search)</span>',
z=' <input type="text" style="width: 10em" class="CodeMirror-search-field"/> <span style="color: #888" class="CodeMirror-search-hint">(Use /re/ syntax for regexp search)</span>',A='With: <input type="text" style="width: 10em" class="CodeMirror-search-field"/>',B="Replace? <button>Yes</button> <button>No</button> <button>All</button> <button>Stop</button>";f.commands.find=function(a){j(a);g(a)};f.commands.findPersistent=function(a){j(a);g(a,!1,!0)};f.commands.findPersistentNext=function(a){g(a,!1,
!0,!0)};f.commands.findPersistentPrev=function(a){g(a,!0,!0,!0)};f.commands.findNext=g;f.commands.findPrev=function(a){g(a,!0)};f.commands.clearSearch=j;f.commands.replace=u;f.commands.replaceAll=function(a){u(a,!0)}});
