var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,g,c){b instanceof String&&(b=String(b));for(var k=b.length,h=0;h<k;h++){var l=b[h];if(g.call(c,l,h,b))return{i:h,v:l}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,g,c){b!=Array.prototype&&b!=Object.prototype&&(b[g]=c.value)};$jscomp.getGlobal=function(b){b=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,b];for(var g=0;g<b.length;++g){var c=b[g];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,g,c,k){if(g){c=$jscomp.global;b=b.split(".");for(k=0;k<b.length-1;k++){var h=b[k];h in c||(c[h]={});c=c[h]}b=b[b.length-1];k=c[b];g=g(k);g!=k&&null!=g&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
(function(b){"object"==typeof exports&&"object"==typeof module?b(require("../../lib/codemirror"),require("./searchcursor"),require("../dialog/dialog")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","./searchcursor","../dialog/dialog"],b):b(CodeMirror)})(function(b){function g(a,d){"string"==typeof a?a=new RegExp(a.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&"),d?"gi":"g"):a.global||(a=new RegExp(a.source,a.ignoreCase?"gi":"g"));return{token:function(d){a.lastIndex=d.pos;
var b=a.exec(d.string);if(b&&b.index==d.pos)return d.pos+=b[0].length||1,"searching";b?d.pos=b.index:d.skipToEnd()}}}function c(){this.overlay=this.posFrom=this.posTo=this.lastQuery=this.query=null}function k(a){return a.state.search||(a.state.search=new c)}function h(a){return"string"==typeof a&&a==a.toLowerCase()}function l(a,d,b){return a.getSearchCursor(d,b,h(d))}function y(a,d,b,f,e){a.openDialog(d,f,{value:b,selectValueOnOpen:!0,closeOnEnter:!1,onClose:function(){n(a)},onKeyDown:e})}function r(a,
d,b,f,e){a.openDialog?a.openDialog(d,e,{value:f,selectValueOnOpen:!0}):e(prompt(b,f))}function z(a,b,c,f){if(a.openConfirm)a.openConfirm(b,f);else if(confirm(c))f[0]()}function u(a){return a.replace(/\\(.)/g,function(a,b){return"n"==b?"\n":"r"==b?"\r":b})}function v(a){var b=a.match(/^\/(.*)\/([a-z]*)$/);if(b)try{a=new RegExp(b[1],-1==b[2].indexOf("i")?"":"i")}catch(A){}else a=u(a);if("string"==typeof a?""==a:a.test(""))a=/x^/;return a}function p(a,b,c){b.queryText=c;b.query=v(c);a.removeOverlay(b.overlay,
h(b.query));b.overlay=g(b.query,h(b.query));a.addOverlay(b.overlay);a.showMatchesOnScrollbar&&(b.annotate&&(b.annotate.clear(),b.annotate=null),b.annotate=a.showMatchesOnScrollbar(b.query,h(b.query)))}function m(a,d,c,f){var e=k(a);if(e.query)return q(a,d);var g=a.getSelection()||e.lastQuery;if(c&&a.openDialog){var t=null,h=function(d,c){b.e_stop(c);d&&(d!=e.queryText&&(p(a,e,d),e.posFrom=e.posTo=a.getCursor()),t&&(t.style.opacity=1),q(a,c.shiftKey,function(b,d){var e;3>d.line&&document.querySelector&&
(e=a.display.wrapper.querySelector(".CodeMirror-dialog"))&&e.getBoundingClientRect().bottom-4>a.cursorCoords(d,"window").top&&((t=e).style.opacity=.4)}))};y(a,'Search: <input type="text" style="width: 10em" class="CodeMirror-search-field"/> <span style="color: #888" class="CodeMirror-search-hint">(Use /re/ syntax for regexp search)</span>',g,h,function(d,e){var c=b.keyName(d),f=b.keyMap[a.getOption("keyMap")][c];f||(f=a.getOption("extraKeys")[c]);if("findNext"==f||"findPrev"==f||"findPersistentNext"==
f||"findPersistentPrev"==f)b.e_stop(d),p(a,k(a),e),a.execCommand(f);else if("find"==f||"findPersistent"==f)b.e_stop(d),h(e,d)});f&&g&&(p(a,e,g),q(a,d))}else r(a,'Search: <input type="text" style="width: 10em" class="CodeMirror-search-field"/> <span style="color: #888" class="CodeMirror-search-hint">(Use /re/ syntax for regexp search)</span>',"Search for:",g,function(b){b&&!e.query&&a.operation(function(){p(a,e,b);e.posFrom=e.posTo=a.getCursor();q(a,d)})})}function q(a,d,c){a.operation(function(){var f=
k(a),e=l(a,f.query,d?f.posFrom:f.posTo);if(!e.find(d)&&(e=l(a,f.query,d?b.Pos(a.lastLine()):b.Pos(a.firstLine(),0)),!e.find(d)))return;a.setSelection(e.from(),e.to());a.scrollIntoView({from:e.from(),to:e.to()},20);f.posFrom=e.from();f.posTo=e.to();c&&c(e.from(),e.to())})}function n(a){a.operation(function(){var b=k(a);if(b.lastQuery=b.query)b.query=b.queryText=null,a.removeOverlay(b.overlay),b.annotate&&(b.annotate.clear(),b.annotate=null)})}function w(a,b,c){a.operation(function(){for(var d=l(a,
b);d.findNext();)if("string"!=typeof b){var e=a.getRange(d.from(),d.to()).match(b);d.replace(c.replace(/\$(\d)/g,function(a,b){return e[b]}))}else d.replace(c)})}function x(a,b){if(!a.getOption("readOnly")){var d=a.getSelection()||k(a).lastQuery,c=b?"Replace all:":"Replace:";r(a,c+' <input type="text" style="width: 10em" class="CodeMirror-search-field"/> <span style="color: #888" class="CodeMirror-search-hint">(Use /re/ syntax for regexp search)</span>',c,d,function(e){e&&(e=v(e),r(a,'With: <input type="text" style="width: 10em" class="CodeMirror-search-field"/>',
"Replace with:","",function(d){d=u(d);if(b)w(a,e,d);else{n(a);var c=l(a,e,a.getCursor("from")),f=function(){var b=c.from(),h;if(!(h=c.findNext())&&(c=l(a,e),!(h=c.findNext())||b&&c.from().line==b.line&&c.from().ch==b.ch))return;a.setSelection(c.from(),c.to());a.scrollIntoView({from:c.from(),to:c.to()});z(a,"Replace? <button>Yes</button> <button>No</button> <button>All</button> <button>Stop</button>","Replace?",[function(){g(h)},f,function(){w(a,e,d)}])},g=function(a){c.replace("string"==typeof e?
d:d.replace(/\$(\d)/g,function(b,c){return a[c]}));f()};f()}}))})}}b.commands.find=function(a){n(a);m(a)};b.commands.findPersistent=function(a){n(a);m(a,!1,!0)};b.commands.findPersistentNext=function(a){m(a,!1,!0,!0)};b.commands.findPersistentPrev=function(a){m(a,!0,!0,!0)};b.commands.findNext=m;b.commands.findPrev=function(a){m(a,!0)};b.commands.clearSearch=n;b.commands.replace=x;b.commands.replaceAll=function(a){x(a,!0)}});
